# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

snapshot:
  version_template: "{{ incpatch .Version }}-next"

gomod:
  proxy: true

git:
  ignore_tags:
    - "{{ if not .IsNightly }}nightly{{ end }}"

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./main.go
    binary: gh-custom-property-manager
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/hi120ki/gh-custom-property-manager/cmd.version={{.Version}} -X github.com/hi120ki/gh-custom-property-manager/cmd.commit={{.Commit}} -X github.com/hi120ki/gh-custom-property-manager/cmd.date={{.Date}}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]
    builds_info:
      group: root
      owner: root
      mtime: "{{ .CommitDate }}"
    files:
      - src: README.md
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"
      - src: LICENSE
        info:
          owner: root
          group: root
          mtime: "{{ .CommitDate }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^build:"
      - "^style:"
      - "^refactor:"
      - "^perf:"
  groups:
    - title: "New Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?(fix|bug)(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other work"
      order: 999

release:
  github:
    owner: hi120ki
    name: gh-custom-property-manager
  name_template: "{{.ProjectName}} v{{.Version}}"

nfpms:
  - file_name_template: '{{ .ConventionalFileName }}'
    homepage: https://github.com/hi120ki/gh-custom-property-manager
    description: A CLI tool for efficiently managing GitHub repository custom properties
    maintainer: Hi120ki <12624257+hi120ki@users.noreply.github.com>
    license: MIT
    vendor: Hi120ki
    bindir: /usr/bin
    section: utils
    mtime: "{{ .CommitDate }}"
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/gh-custom-property-manager/copyright
        file_info:
          mode: 0644
          mtime: "{{ .CommitDate }}"
    formats:
      - deb
      - rpm
      - apk
      - archlinux
